name: "Remoti: finding remote jobs"
description: "Find, filter and save remote jobs"
full_description: "Remote jobs are becoming more and more popular nowadays and with Remoti you can search for them on your iPhone and apply for them. Find work in categories such as software development, QA, product, legal, design, and many more. You can also save interesting jobs to your phone so you can see them at any time!"
android: https://play.google.com/store/apps/details?id=me.manulorenzo.remoti
iOS: https://apps.apple.com/nl/app/remoti/id1567902235
web: false
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
# producthunt: https://telegra.ph/Replace-this-link-07-23
# companies:
#   - url: https://telegra.ph/Replace-this-link-07-23
#     image: androidpolice.png
#   - url: https://telegra.ph/Replace-this-link-07-23
#     image: producthunt.png